<!-- /.content-wrapper -->
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 2.3.8
  </div>
  <strong>Copyright &copy; 2014-2016 <a href="http://3sgroup.vn">3SGROUP</a>.</strong> All rights reserved.
</footer>
<div class="loading-block">
    <div class="loading-block-container">
        <div class="lds-css ng-scope">
            <div class="lds-spin" style="width:100%;height:100%"><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div></div>
        </div>
    </div>
</div>
