services:
  web-qtair:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qt_d7_web
    depends_on:
      - db
    ports:
      - "18080:80"
    volumes:
      - ./:/var/www/html
    environment:
      TZ: Asia/Ho_Chi_Minh
    restart: unless-stopped

  db:
    image: mariadb:10.5
    container_name: qt_d7_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "13306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root_local_change_me
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal_local_change_me
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - d7_db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  d7_db_data:
