<div class="block-benefits">
    <div class="block-container container">
        <div class="block-title">
<!--            <h2 class="title-type-1">--><?php //print(t("Only for Autic Family")); ?><!--</h2>-->
            <h2 class="title-type-1">DÀNH RIÊNG CHO THÀNH VIÊN AUTIC FAMILY</h2>

        </div>
        <div class="block-des">
<!--            --><?php //print(t("Login or register to do business with Acoustic")); ?>
<!--            <a href="/agent/login">Đăng nhập</a> hoặc <a href="/user/register">đăng ký</a> để nhận ngay ưu đãi từ Autic.vn-->
            Chương trình đại lí thân thiết của Autic. <a href="#" class="register-block_family">Đăng ký</a> ngay để nhận được ưu đãi từ Autic
        </div>
        <div class="block-detail">
            <a href="#" class="register-block_family">Tham gia ngay</a>
        </div>
    </div> 
</div>