<?php
/**
 * Implements hook_install().
 */
function cassiopeia_address_install() {

}
function cassiopeia_address_schema() {
    $schema = array();
    $schema['cassiopeia_address_province'] = array(
        'fields' => array(
            'id'=> array(
                'type' => 'serial',
                'unsigned' => TRUE,
                'not null' => TRUE,
            ),
            'code' => array(
                'type' => 'varchar',
                'length' => 255,
                'default' => '',
            ),
            'name' => array(
                'type' => 'varchar',
                'length' => 255,
                'default' => '',
            ),
            'uid' => array(
                'type' => 'int',
                'not null' => TRUE,
                'default' => 0,
            ),
            'created' => array(
                'type' => 'int',
                'not null' => TRUE,
                'default' => 0,
            ),
            'changed' => array(
                'type' => 'int',
                'default' => 0,
            ),
        ),
        'primary key' => array('id'),
        'unique keys' => array(

        ),
        'indexes' => array(
            'c_address_province_name'     => array('name'),
            'c_address_province_code'     => array('code'),
            'c_address_province_uid'     => array('uid'),
            'c_address_province_created' => array('created'),
            'c_address_province_changed' => array('changed'),
        ),
    );
    $schema['cassiopeia_address_district'] = array(
        'fields' => array(
            'id'=> array(
                'type' => 'serial',
                'unsigned' => TRUE,
                'not null' => TRUE,
            ),
            'name' => array(
                'type' => 'varchar',
                'length' => 255,
                'default' => '',
            ),
            'uid' => array(
                'type' => 'int',
                'not null' => TRUE,
                'default' => 0,
            ),
            'pid' => array(
                'type' => 'int',
                'not null' => TRUE,
                'default' => 0,
            ),
            'created' => array(
                'type' => 'int',
                'not null' => TRUE,
                'default' => 0,
            ),
            'changed' => array(
                'type' => 'int',
                'default' => 0,
            ),
        ),
        'primary key' => array('id'),
        'unique keys' => array(

        ),
        'indexes' => array(
            'c_address_district_name'     => array('name'),
            'c_address_district_uid'     => array('uid'),
            'c_address_district_created' => array('created'),
            'c_address_district_changed' => array('changed'),
        ),
    );
    $schema['cassiopeia_address_ward'] = array(
        'fields' => array(
            'id'=> array(
                'type' => 'serial',
                'unsigned' => TRUE,
                'not null' => TRUE,
            ),
            'name' => array(
                'type' => 'varchar',
                'length' => 255,
                'default' => '',
            ),
            'prefix' => array(
                'type' => 'varchar',
                'length' => 255,
                'default' => '',
            ),
            'did' => array(
                'type' => 'int',
                'not null' => TRUE,
                'default' => 0,
            ),
            'pid' => array(
                'type' => 'int',
                'not null' => TRUE,
                'default' => 0,
            ),
            'uid' => array(
                'type' => 'int',
                'not null' => TRUE,
                'default' => 0,
            ),
            'created' => array(
                'type' => 'int',
                'not null' => TRUE,
                'default' => 0,
            ),
            'changed' => array(
                'type' => 'int',
                'default' => 0,
            ),
        ),
        'primary key' => array('id'),
        'unique keys' => array(

        ),
        'indexes' => array(
            'c_address_district_name'     => array('name'),
            'c_address_district_prefix'     => array('prefix'),
            'c_address_district_uid'     => array('uid'),
            'c_address_district_created' => array('created'),
            'c_address_district_changed' => array('changed'),
        ),
    );
    return $schema;
}
/**
 * Implements hook_uninstall().
 */
function cassiopeia_address_uninstall() {
    db_drop_table('cassiopeia_address_booking');

}
function cassiopeia_address_update_7101() {
   $int = array(
       'type' => 'int',
       'not null' => TRUE,
       'default' => 0,
   );
    db_add_field('cassiopeia_address_district', 'pid',$int);
    db_add_field('cassiopeia_address_ward', 'pid',$int);
    db_add_field('cassiopeia_address_ward', 'did',$int);
}